### ISSUE TITLE
Pillow missing from requirements.txt

### ISSUE THREAD

**Issue by Q-efx** [Torantulino/Auto-GPT#493] opened 2023-04-08 14:59 UTC
### Duplicates

- [X] I have searched the existing issues

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by richbeales** [comment] 2023-04-08 16:15
duplicate of https://github.com/Torantulino/Auto-GPT/issues/481

**Comment by BogNogga** [comment] 2023-04-08 16:21
pip install Pillow

**Comment by richbeales** [comment] 2023-04-08 16:22
Will be solved by https://github.com/Torantulino/Auto-GPT/pull/482

**Closed** 2023-04-09 07:08 UTC
