### ISSUE TITLE
TypeError: chat_with_ai() takes 5 positional arguments but 6 were given

### ISSUE THREAD

**Issue by fredadun** [Torantulino/Auto-GPT#684] opened 2023-04-10 13:12 UTC
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Traceback (most recent call last):
  File "C:\Users\xxxx\Auto-GPT\scripts\main.py", line 318, in <module>
    assistant_reply = chat.chat_with_ai(

TypeError: chat_with_ai() takes 5 positional arguments but 6 were given

**Comment by Torantulino** [comment] 2023-04-10 13:14
Duplicate of #676

**Closed by Torantulino** 2023-04-10 13:14 UTC
Labels: duplicate
