### ISSUE TITLE
TypeError: chat_with_ai() takes 5 positional arguments but 6 were give

### ISSUE THREAD

**Issue by akamalov** [Torantulino/Auto-GPT#687] opened 2023-04-10 13:16 UTC
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

*Version:*

```master 643ca9d Merge pull request #664 from blankster/patch-2```

*Proceed with command:*

```

(base) D:\GPT\Auto-GPT>python scripts\main.py
Welcome back!  Would you like me to return to being shopbot?
Continue with the last settings?
Name:  shopbot
Role:  browse to amazon.com
Goals: ['look for nvidia geforce rtx 4090 24GB graphics card', 'get prices from lowest to  highest', 'write the output to csv file named nvidia.txt', 'shutdown']
Continue (y/n): y
Using memory of type: LocalCache
Traceback (most recent call last):
  File "D:\GPT\Auto-GPT\scripts\main.py", line 318, in <module>
    assistant_reply = chat.chat_with_ai(
TypeError: chat_with_ai() takes 5 positional arguments but 6 were given

(base) D:\GPT\Auto-GPT>

```

### Environment file
```
#PINECONE_API_KEY=your-pinecone-api-key
#PINECONE_ENV=your-pinecone-region
OPENAI_API_KEY="########## Edited #############"
#ELEVENLABS_API_KEY=your-elevenlabs-api-key
SMART_LLM_MODEL="gpt-4"
FAST_LLM_MODEL="gpt-3.5-turbo"
#GOOGLE_API_KEY=
#CUSTOM_SEARCH_ENGINE_ID=
USE_AZURE=False
#OPENAI_API_BASE=your-base-url-for-azure
#OPENAI_API_VERSION=api-version-for-azure
#OPENAI_DEPLOYMENT_ID=deployment-id-for-azure
```
### Current behavior 😯

Errors out complaining ```TypeError: chat_with_ai() takes 5 positional arguments but 6 were given```

### Expected behavior 🤔

It should return a result

### Your prompt 📝

```
python scripts\main.py

```

**Comment by Torantulino** [comment] 2023-04-10 13:19
Duplicate of #676

Please check existing issues before submitting.

**Closed by Torantulino** 2023-04-10 13:19 UTC
