### ISSUE TITLE
scripts/json_parser.py   substring not found

### ISSUE THREAD

**Issue by giovannimanzoni** [Torantulino/Auto-GPT#793] opened 2023-04-11 11:30 UTC
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

From last update, ask a question and after thinking:

Error:        
 Traceback (most recent call last): File "/home/gpt1/Auto-GPT/scripts/main.py", line 76, in print_assistant_thoughts assistant_reply_json = fix_and_parse_json(assistant_reply) File "/home/gpt1/Auto-GPT/scripts/json_parser.py", line 51, in fix_and_parse_json brace_index = json_str.index("{") ValueError: substring not found

### Current behavior 😯

error

### Expected behavior 🤔

response without error

### Your prompt 📝

```yaml
# verwandelt den folgenden Text,in einem SEO Text von 200 Wörtern: bla mit „Marke „ oder „Brandzeichen“. bla...
```

**Comment by richbeales** [comment] 2023-04-11 11:53
Dupe of
https://github.com/Torantulino/Auto-GPT/issues/751
https://github.com/Torantulino/Auto-GPT/issues/726
https://github.com/Torantulino/Auto-GPT/issues/626
https://github.com/Torantulino/Auto-GPT/issues/601

etc.

**Comment by james431987** [comment] 2023-04-11 15:03
it threw that error 10 times in a row for me. I thought I was going to have to close the program, but got past it. Any fix for this?

**Comment by zajerao** [comment] 2023-04-11 15:17
same problem here, just  tiny difference, error seems to be at line 78 instead, if that is helpful. 
14:29:07,596 AutoGPT INFO Error: 
: Traceback (most recent call last):
  File "/Users/a/Auto-GPT/scripts/main.py", line 78, in print_assistant_thoughts
    assistant_reply_json = fix_and_parse_json(assistant_reply)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a/Auto-GPT/scripts/json_parser.py", line 51, in fix_and_parse_json
    brace_index = json_str.index("{")
                  ^^^^^^^^^^^^^^^^^^^
ValueError: substring not found

Is there a version or build number to check to know exactly what I am running?

**Comment by james431987** [comment] 2023-04-11 16:05
I found this #808  and did the code changes. I haven't gotten a JSON error since.

Now I have a different problem where it decides it's tired after a while and just does nothing as the command repeatedly..

**Comment by hanskraut31312312** [comment] 2023-04-12 08:48
me too "substring not found" on every user input :(

Auto-GPT wont react to it. But the "do nothing sickness" from yesterday work again. (removed the do nothing command temporarily)

NEXT ACTION: COMMAND = list_agents ARGUMENTS = {}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for AI_GPT_8...
Input:Whenever i give userfeedback there is a error and you dont seem to react to it. Please fix.
SYSTEM: Human feedback: Whenever i give userfeedback there is a error and you dont seem to react to it. Please fix.
Error:
Traceback (most recent call last): File "scripts/main.py", line 76, in print_assistant_thoughts assistant_reply_json = fix_and_parse_json(assistant_reply) File "C:\Programming\Auto-GPT_AI_8\scripts\json_parser.py", line 51, in fix_and_parse_json brace_index = json_str.index("{") ValueError: substring not found
NEXT ACTION: COMMAND = Error: ARGUMENTS = substring not found

**Comment by richbeales** [comment] 2023-04-12 19:43
closed as duplicate

**Closed by richbeales** 2023-04-12 19:43 UTC
