### ISSUE TITLE
Unable to install requirements

### ISSUE THREAD

**Issue by arbuge** [Torantulino/Auto-GPT#43] opened 2023-04-02 20:06 UTC
![image](https://user-images.githubusercontent.com/2955137/229376413-5a084aeb-ff4e-4f05-9c26-2c9613803250.png)

Getting this error when trying to install.

**Comment by mattjoyce** [comment] 2023-04-02 20:34
I removed the version requirement for the following.
**beautifulsoup4**
colorama==0.4.6
**googlesearch_python
openai**
playsound==1.2.2
readability_lxml==0.8.1
**requests
docker**

That allowed pip to complete, but I have no idea if that will satisfy actual requirements.

**Comment by easy-peasy** [comment] 2023-04-03 01:30
@arbuge please close this ticket as duplicate of https://github.com/Torantulino/Auto-GPT/issues/30

**Closed** 2023-04-03 01:53 UTC
Labels: duplicate
