### ISSUE TITLE
Mostly getting 'Command = Do_nothing'. any idea how to correct that.

### ISSUE THREAD

**Issue by Natsu-Dragneel-Aka** [Torantulino/Auto-GPT#950] opened 2023-04-12 13:00 UTC
### Duplicates

- [X] I have searched the existing issues

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by onekum** [comment] 2023-04-12 13:20
Dupe of #830

**Closed** 2023-04-12 14:03 UTC
