### ISSUE TITLE
Invalid JSON error

### ISSUE THREAD

**Issue by Koningsbruggen** [Torantulino/Auto-GPT#787] opened 2023-04-11 10:32 UTC
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

from Discord, same issue from multiple folks

Error:
 Traceback (most recent call last): File "/Users/joeyvankoningsbruggen/Desktop/AUTO-GPT/Auto-GPT/scripts/main.py", line 78, in print_assistant_thoughts assistant_reply_json = fix_and_parse_json(assistant_reply) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/joeyvankoningsbruggen/Desktop/AUTO-GPT/Auto-GPT/scripts/json_parser.py", line 51, in fix_and_parse_json brace_index = json_str.index("{") ^^^^^^^^^^^^^^^^^^^ ValueError: substring not found
Koningsbruggen — vandaag om 11:01
hmm used GPT4 to fix the issue in json_parser.py
ah no it came back haha, frustrating
Koningsbruggen — vandaag om 11:25
it just throws up tese endless errors everytime eventually

Unicron — vandaag om 11:43
SYSTEM:  Command Error: threw the following error: substring not found
Error:
 Traceback (most recent call last): File "D:\Auto-GPT\scripts\main.py", line 76, in print_assistant_thoughts assistant_reply_json = fix_and_parse_json(assistant_reply) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Auto-GPT\scripts\json_parser.py", line 51, in fix_and_parse_json brace_index = json_str.index("{") ^^^^^^^^^^^^^^^^^^^ ValueError: substring not found
NEXT ACTION:  COMMAND = Error: ARGUMENTS = substring not found
SYSTEM:  Command Error: threw the following error: substring not found

### Current behavior 😯

throws up an error, seems to occur randomly, sometimes gets stuck in an error loop

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by richbeales** [comment] 2023-04-11 10:38
Dupe of 
https://github.com/Torantulino/Auto-GPT/issues/751
https://github.com/Torantulino/Auto-GPT/issues/726
https://github.com/Torantulino/Auto-GPT/issues/626
https://github.com/Torantulino/Auto-GPT/issues/601

etc.

**Comment by Koningsbruggen** [comment] 2023-04-11 11:33
sorry I did search before but did not see those

**Comment by richbeales** [comment] 2023-04-12 10:31
closing as duplicate

**Closed by richbeales** 2023-04-12 10:31 UTC
